services:
    go-template-web:
        image: go-template-web
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        container_name: go-template-web
        environment:
            - HOST=
        ports:
            - "8080:8080"
            - "2345:2345"
        volumes:
            - ./:/app
            - /app/bin
